### ISSUE TITLE
Exclude entry

### ISSUE THREAD

**Issue by camdagr8** [gcds/webpack-glob-entries#4]
Is there a way to exclude a file from the entry? 

For instance i have: 

If I have this as my entry:
`'/scripts/**/*.js'`

But want to exclude this:
`'/scripts/src/*.js'`

How would I handle that?

**Comment by aurimasniekis** [comment]
The end result is array you can just filter out that you do not need. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
