### ISSUE TITLE
Does it work on webpack 4?

### ISSUE THREAD

**Issue by devope** [gcds/webpack-glob-entries#5]
I got en error:
> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

My config:
`const WebpackGlobEntries = require('webpack-glob-entries');`

`module.exports = {  `
`  entry:  {`
`    ComponentsCommon_Js: WebpackGlobEntries('./Components/**/js/*.js'),`

**Comment by omidnikrah** [comment]
I have the same issue.

**Comment by ImSeaWorld** [comment]
No, but you can do this using ``glob`` in the same context as the plugin. This would go in your ``webpack.config.js``

```js
const glob = require('glob');

var entries = []; // add defaults if you'd like
var files = glob.sync('./Components/**/js/*.js');
for (var i = 0; i < files.length; i++) {
    entries.push(files[i]);
}

module.exports = {
   ...
    entry: entries,
   ...
}
```

This was the fix I went with. Assigning keys to the array is ultimately the issue with this plugin and wont work on newer revisions of webpack.

**Comment by qkreltms** [comment]
It works well with webpack5

**Comment by aurimasniekis** [comment]
Sorry, but I am not maintaining this anymore if it works with WebPack5 then it's good but if something doesn't work, and you know fix I am up for a pull request to fix this.
